Repository ManageIQ/manageiq-schema, pull requests merged in 2018-04, with the labels that each got.

#184 Update provider_region to nil for Google provider
  db/migrate/20180405145642_remove_provider_region_for_google_provider.rb
  spec/migrations/20180405145642_remove_provider_region_for_google_provider_spec.rb
Labels: blocker, bug

#166 Remove all VMware MKS console-related records from SettingSchanges
  db/migrate/20180130165200_drop_webmks.rb
  spec/migrations/20180130165200_drop_webmks_spec.rb
Labels: data

#191 Nil MiqDatabase#update_repo_name
  db/migrate/20160913195129_move_repo_data_from_database_to_settings.rb
  spec/migrations/20160913195129_move_repo_data_from_database_to_settings_spec.rb
Labels: gaprindashvili/yes

#185 Creating physical_network_ports table
  db/migrate/20180409120422_create_physical_network_ports.rb
Labels: providers/physical, schema

#192 Azure backslash to forward slash
  db/migrate/20180424141617_azure_backslash_to_forward_slash.rb
  spec/migrations/20180424141617_azure_backslash_to_forward_slash_spec.rb
Labels: bug, data, providers/cloud
