Repository ManageIQ/manageiq-schema, pull requests merged in 2018-10, with the labels that each got.

#281 Add conversion_host_id to miq_request_task
  db/migrate/20181001131632_add_conversion_host_id_to_miq_request_tasks.rb
  spec/migrations/20181001131632_add_conversion_host_id_to_miq_request_tasks_spec.rb
Labels: gaprindashvili/no, hammer/no, schema, transformation

#286 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Schema.pot
  locale/en/ManageIQ_Schema.po
  locale/es/ManageIQ_Schema.po
  locale/fr/ManageIQ_Schema.po
  locale/ja/ManageIQ_Schema.po
  locale/pt_BR/ManageIQ_Schema.po
  locale/zh_CN/ManageIQ_Schema.po
  zanata.xml
Labels: internationalization

#287 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#292 Bump Travis to PG 9.5
  .travis.yml
Labels: test

#285 Add ID references to PhysicalDisks and Canisters
  db/migrate/20181003122633_add_canister_id_and_ems_ref_to_physical_disks.rb
Labels: enhancement, providers/physical

#294 [Changelog] Add Sprint 97 and Hammer Beta1 updates
  CHANGELOG.md
Labels: documentation

#291 Add tenant_id to miq_product_features
  db/migrate/20181023171353_add_tenant_id_and_tenant_node_to_miq_product_features.rb
Labels: blocker
