Repository ManageIQ/manageiq-schema, pull requests merged in 2018-09, with the labels that each got.

#254 Add cancelation_status column in MiqRequest and MiqRequestTask
  db/migrate/20180813141056_add_cancelation_status_to_miq_request.rb
Labels: enhancement, schema

#270 Remove column report_base_model from ChargebackRate table
  db/migrate/20180905144610_remove_report_base_model_from_chargeback_rate.rb
Labels: enhancement, schema

#259 Swift DB Backups Requirements
  db/migrate/20180817212259_add_api_version_and_domain_id_and_security_protocol_and_openstack_region_to_file_depot.rb
Labels: enhancement

#267 Add table for service instances
  db/migrate/20180827083140_create_service_instances_table.rb
Labels: enhancement

#271 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#266 Add a "migrations_ran" column to miq_regions
  db/migrate/20171031000000_add_migrations_ran_to_miq_regions.rb
Labels: blocker, bug

#272 Add limits colums to conversion_hosts table
  db/migrate/20180917151300_add_limits_to_conversion_host.rb
Labels: gaprindashvili/no, schema, transformation

#276 PhysicalDisk#type wasn't being used for STI
  db/migrate/20180924144957_rename_physical_disk_type.rb
Labels: bug, providers/physical, technical debt

#275 Maintenance zone support for suspending provider
  db/migrate/20180618083035_add_visible_to_zone.rb
  db/migrate/20180618084054_init_zones_visibility.rb
  db/migrate/20180618084757_add_zone_before_pause_id_to_ext_management_system.rb
  db/migrate/20180920085721_add_maintenance_zone_id_to_region.rb
  spec/migrations/20180618084054_init_zones_visibility_spec.rb
Labels: enhancement

#279 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation

#278 Fix incorrectly tenant default groups
  db/migrate/20180926152238_fix_default_tenant_group.rb
  spec/migrations/20180926152238_fix_default_tenant_group_spec.rb
Labels: hammer/yes
