Repository ManageIQ/manageiq-schema, pull requests merged in 2018-08, with the labels that each got.

#201 Optimize migration which creates task for each job
  db/migrate/20170120164058_create_task_for_each_job_and_transfer_attributes.rb
  spec/migrations/20170120164058_create_task_for_each_job_and_transfer_attributes_spec.rb
Labels: gaprindashvili/yes, performance

#235 Remove Host Provisioning references
  db/migrate/20180712122000_remove_host_provisioning.rb
  spec/migrations/20180712122000_remove_host_provisioning_spec.rb
Labels: technical debt

#230 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#244 Add a version to the more_core_extensions dependency
  manageiq-schema.gemspec
Labels: dependencies

#246 Change backtick to single quote
  db/migrate/20180712122000_remove_host_provisioning.rb
Labels: bug

#238 Add internal column to ServiceTemplate table
  db/migrate/20180719163110_add_internal_to_service_template.rb
  spec/migrations/20180719163110_add_internal_to_service_template_spec.rb
Labels: blocker, transformation

#245 Add a STI disabled spec
  db/migrate/20160829134746_remove_atomic_container_providers.rb
  db/migrate/20170217220618_remove_central_admin_region_auth_records.rb
  db/migrate/20170222105117_remove_openshift_enterprise_provider.rb
  db/migrate/20170222214902_add_initiator_to_service.rb
  db/migrate/20170409083720_add_enabled_field_to_ems.rb
  db/migrate/20170704102536_use_deleted_on_in_containers_tables.rb
  db/migrate/20170718111834_unify_container_definition_and_container.rb
  db/migrate/20171117201600_downcase_resource_group_ems_ref_for_azure.rb
  spec/support/database_helper.rb
  spec/support/migration_helper.rb
Labels: bug, enhancement, test

#249 Remove Settings.product.transformation - add missing specs
  spec/migrations/20180718132840_remove_transformation_product_setting_spec.rb
Labels: data, gaprindashvili/no, test, transformation

#247 Add a test requiring data migrations to have an associated spec file
  spec/automated_review/data_migrations_need_tests_spec.rb
  spec/support/constant_watcher.rb
Labels: bug, enhancement, test

#248 Ensure id and *_id columns are bigint
  spec/automated_review/id_columns_are_bigint_spec.rb
Labels: enhancement, test

#253 Don't execute the changelog
  CHANGELOG.md
Labels: documentation

#255 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#257 Add version dependency for activerecord-id_regions
  manageiq-schema.gemspec
Labels: bug/sporadic test failure, test

#251 Update default of internal attribute in service template
  db/migrate/20180810144738_update_default_internal_attribute.rb
  spec/migrations/20180810144738_update_default_internal_attribute_spec.rb
Labels: data, enhancement, gaprindashvili/no, transformation

#215 Migrate Nuage CloudSubnet default type to new subclass
  db/migrate/20180607084710_nuage_subclass_l3_cloud_subnet.rb
  spec/migrations/20180607084710_nuage_subclass_l3_cloud_subnet_spec.rb
Labels: data

#258 Model relation "SecurityGroup belongs to NetworkRouter or CloudSubnet"
  db/migrate/20180817152200_add_network_router_id_to_security_group.rb
  db/migrate/20180817152201_add_cloud_subnet_id_to_security_group.rb
Labels: enhancement

#260 Create OpenShift Service Catalog tables
  db/migrate/20180821112856_create_service_catalog_tables.rb
Labels: enhancement

#265 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation
