Repository ManageIQ/manageiq-schema, pull requests merged in 2018-03, with the labels that each got.

#174 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#176 Add vm_ems_ref to event_streams
  db/migrate/20180313135925_add_vm_ems_ref_to_event_streams.rb
Labels: enhancement

#161 Remove all instances of ManageIQ::Providers::Hawkular::MiddlewareManager from ext_management_systems
  db/migrate/20180129152935_remove_hawkular_ems.rb
  spec/migrations/20180129152935_remove_hawkular_ems_spec.rb
Labels: gaprindashvili/no

#169 Add compliance information
  db/migrate/20180209180035_add_compliance_information_to_physical_servers.rb
Labels: enhancement, schema
