Repository ManageIQ/manageiq-schema, pull requests merged in 2018-02, with the labels that each got.

#154 Drop BinaryBlobPart#md5 and #size
  db/migrate/20180112171348_drop_unnecessary_blob_parts_md5.rb
  spec/migrations/20180112171348_drop_unnecessary_blob_parts_md5_spec.rb
Labels: data, gaprindashvili/no, schema, technical debt

#163 [Changelog] Update for Sprint 78 and Gaprindashvili-1 release
  CHANGELOG.md
Labels: documentation

#172 Add last_updated_on to configuration_script_sources
  db/migrate/20180219151037_add_last_updated_on_to_configuration_script_source.rb
Labels: enhancement, providers/automation

#168 Add hostname to Vm
  db/migrate/20180215164010_add_hostname_to_vm.rb
Labels: enhancement
