Repository ManageIQ/manageiq-schema, pull requests merged in 2018-06, with the labels that each got.

#225 Fix the quadicon settings migration for users without quadicon settings
  db/migrate/20180606083431_convert_quadicon_settings_keys.rb
  spec/migrations/20180606083431_convert_quadicon_settings_keys_spec.rb
Labels: bug, gaprindashvili/no

#220 Add a Status column to Storages
  db/migrate/20180611131314_add_status_to_storages.rb
Labels: enhancement

#221 Add Firmware Type to Hardwares
  db/migrate/20180613200937_add_firmware_type_to_hardware.rb
Labels: enhancement

#226 Add ems_ref to lans to help with unique listing
  db/migrate/20180625120055_add_ems_ref_to_lans.rb
Labels: enhancement

#199 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation
