Repository ManageIQ/manageiq-schema, pull requests merged in 2018-11, with the labels that each got.

#298 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Schema.po
  locale/fr/ManageIQ_Schema.po
  locale/ja/ManageIQ_Schema.po
  locale/pt_BR/ManageIQ_Schema.po
  locale/zh_CN/ManageIQ_Schema.po
Labels: internationalization

#299 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#288 Add evm_owner, tenant, group to orch stacks
  db/migrate/20181010134649_add_evm_owner_to_orchestration_stacks.rb
  db/migrate/20181016140921_migrate_orch_stacks_to_have_ownership_concept.rb
  spec/migrations/20181016140921_migrate_orch_stacks_to_have_ownership_concept_spec.rb
Labels: hammer/yes

#305 Default VM connection_state is now 'connected'
  db/migrate/20181119154009_set_vm_connection_state.rb
  spec/migrations/20181119154009_set_vm_connection_state_spec.rb
Labels: data

#306 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#307 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
