Repository ManageIQ/manageiq-schema, pull requests merged in 2018-12, with the labels that each got.

#313 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: changelog/no, gaprindashvili/yes, hammer/yes

#315 Fix travis badge to use the master branch.
  README.md
Labels: developer

#310 Remove worker rows referencing a renamed worker
  db/migrate/20181203224640_remove_renamed_ansible_tower_configuration_manager_refresh_worker_rows.rb
  spec/migrations/20181203224640_remove_renamed_ansible_tower_configuration_manager_refresh_worker_rows_spec.rb
Labels: gaprindashvili/yes, hammer/yes

#316 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#317 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
