Repository ManageIQ/manageiq-schema, pull requests merged in 2019-03, with the labels that each got.

#344 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#348 Don't set version restriction for 'pg' gem
  manageiq-schema.gemspec
Labels: dependencies, hammer/no

#345 Remove container deployments and container deployment nodes
  db/migrate/20190306235417_drop_container_deployments_and_nodes.rb
  db/migrate/20190307131832_removing_authentication_for_container_deployments.rb
  spec/migrations/20190307131832_removing_authentication_for_container_deployments_spec.rb
Labels: technical debt

#351 Fix sporadic failure when role order is different
  spec/migrations/20160127210622_migrate_old_configuration_settings_spec.rb
Labels: bug/sporadic test failure

#352 Remove dependency on manageiq-gems-pending
  Gemfile
  db/migrate/20131118232818_encrypt_miq_database_registration_http_proxy_password_field.rb
  db/migrate/20140301034340_leverage_authentications_for_registration_http_proxy_credentials.rb
  db/migrate/20140409134713_move_log_collection_depot_settings_to_file_depot.rb
  db/migrate/20180606155924_move_ansible_container_secrets_into_database.rb
  db/migrate/20181012161000_remove_special_characters_from_ansible_rabbitmq_password_two.rb
  lib/manageiq/schema.rb
  manageiq-schema.gemspec
  spec/migrations/20131118232818_encrypt_miq_database_registration_http_proxy_password_field_spec.rb
  spec/migrations/20140301034340_leverage_authentications_for_registration_http_proxy_credentials_spec.rb
  spec/migrations/20180606155924_move_ansible_container_secrets_into_database_spec.rb
  spec/migrations/20181012161000_remove_special_characters_from_ansible_rabbitmq_password_two_spec.rb
  spec/spec_helper.rb
Labels: technical debt

#353 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#355 Update supported ruby versions on Travis
  .travis.yml
Labels: test

#356 Add state to services
  db/migrate/20190325160127_add_state_to_services.rb
Labels: enhancement

#359 [HAMMER] Use the gems-pending hammer branch on the schema hammer branch
  Gemfile
Labels: bug, dependencies

#358 Add zone to service templates.
  db/migrate/20190318190517_add_zone_to_service_templates.rb
Labels: enhancement
