Repository ManageIQ/manageiq-schema, pull requests merged in 2019-06, with the labels that each got.

#374 Rename service state to lifecycle_state.
  db/migrate/20190521172822_rename_service_state.rb
Labels: changelog/yes, enhancement

#381 [Changelog] Update for Sprint 113
  CHANGELOG.md
Labels: documentation

#382 Add ansible columns to authentications
  db/migrate/20190613214747_add_ansible_columns_to_authentications.rb
Labels: enhancement, schema

#383 Don't sync the schema_migrations_ran table when adding it
  db/migrate/20171031010000_add_schema_migrations_ran.rb
Labels: bug, hammer/yes

#384 Allow up to 5.1 versioned migrations
  db/migrate/20160127210622_migrate_old_configuration_settings.rb
  manageiq-schema.gemspec
Labels: bug/sporadic test failure, changelog/yes, dependencies

#386 [Changelog] Update for Sprint 114
  CHANGELOG.md
Labels: documentation

#385 Migrate awx credentials to authentications
  db/migrate/20190617191109_move_awx_credentials_to_authentications.rb
  spec/migrations/20190617191109_move_awx_credentials_to_authentications_spec.rb
  spec/migrations/data/20190617191109_move_awx_credentials_to_authentications_spec/credential_attributes.yaml
  spec/migrations/data/20190617191109_move_awx_credentials_to_authentications_spec/vmdb_authentications.yaml
Labels: embedded ansible, enhancement

#387 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes
