Repository ManageIQ/manageiq-schema, pull requests merged in 2019-07, with the labels that each got.

#380 Open URL through automate for various objects
  db/migrate/20190604090631_create_external_urls.rb
Labels: changelog/yes, enhancement, schema

#389 Fix whitespace after linux_admin #208
  spec/migrations/20170512233333_drop_miq_server_rhn_mirror_spec.rb
Labels: changelog/no, test

#391 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#392 Existing services should have a lifecycle state of provisioned
  db/migrate/20190712135032_set_provisioned_state_to_services.rb
  spec/migrations/20190712135032_set_provisioned_state_to_services_spec.rb
Labels: bug, changelog/yes, data

#390 Remove serialization of non-existing classes/objects
  db/migrate/20190708192323_fix_unserializable_notification_options.rb
  spec/migrations/20190708192323_fix_unserializable_notification_options_spec.rb
Labels: bug, changelog/yes

#393 Add git_repository_id to configuration_script_sources
  db/migrate/20190716210326_add_git_repository_to_configuration_script_source.rb
Labels: embedded ansible

#395 Add Authentication to GitRepository
  db/migrate/20190723023214_add_authentication_id_to_git_repository.rb
Labels: embedded ansible, enhancement

#396 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation

#397 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
