Repository ManageIQ/manageiq-schema, pull requests merged in 2019-04, with the labels that each got.

#357 Dialog field - set load_values_on_init to true where show_refresh_button was not enabled
  db/migrate/20190327132620_dialog_field_load_values_on_init.rb
  spec/migrations/20190327132620_dialog_field_load_values_on_init_spec.rb
Labels: hammer/no

#361 [Changelog] Update for Sprint 108
  CHANGELOG.md
Labels: documentation

#362 [GAPRINDASHVILI] Use gems-pending gaprindashvili branch
  Gemfile
Labels: bug, dependencies

#363 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: test

#366 [Changelog] Update for Sprint 109
  CHANGELOG.md
Labels: documentation

#346 Add provider_services_supported column to Availability Zone
  db/migrate/20190305181255_add_provider_services_supported_to_availability_zone.rb
Labels: enhancement, providers/cloud
