Repository ManageIQ/manageiq-schema, pull requests merged in 2019-11, with the labels that each got.

#429 sprint 122
  CHANGELOG.md
Labels: documentation

#433 Remove MiqWidget with content_type set to rss
  db/migrate/20191114131917_remove_miqwidget_rss.rb
  spec/migrations/20191114131917_remove_miqwidget_rss_spec.rb
Labels: ivanchuk/no, technical debt

#435 Subclass ResourcePools
  db/migrate/20191118161213_add_type_to_resource_pools.rb
  db/migrate/20191118161319_subclass_resource_pools.rb
  spec/migrations/20191118161319_subclass_resource_pools_spec.rb
Labels: data, enhancement

#421 Rename table chargeback_rate_detail_currencies to currencies
  db/migrate/20191001174700_rename_chargeback_rate_detail_currency_to_currency.rb
Labels: enhancement

#438 Run bundle install in `bin/setup`
  .travis.yml
  bin/setup
Labels: enhancement

#437 Add miq_worker_types table
  db/migrate/20191115164358_create_miq_worker_types.rb
Labels: enhancement

#426 Remove ems_ref_obj YAML column
  db/migrate/20191023180130_update_openstack_hosts_uid_ems.rb
  db/migrate/20191023180149_add_ems_ref_type.rb
  db/migrate/20191023180330_migrate_ems_ref_obj_to_ems_ref_type.rb
  db/migrate/20191113200451_remove_ems_ref_obj.rb
  spec/migrations/20191023180130_update_openstack_hosts_uid_ems_spec.rb
  spec/migrations/20191023180330_migrate_ems_ref_obj_to_ems_ref_type_spec.rb
Labels: data, schema, technical debt

#439 Replace the server capabilities serialized column with has_vix_disk_lib
  db/migrate/20191122203218_replace_server_capabilities_with_vix_disk_lib.rb
  spec/migrations/20191122203218_replace_server_capabilities_with_vix_disk_lib_spec.rb
Labels: enhancement, technical debt

#417 Add buildtime and url fields to guest_applications
  db/migrate/20190916132550_add_application_build_time.rb
  db/migrate/20190916150002_add_application_url.rb
Labels: enhancement, schema
