Repository ManageIQ/manageiq-schema, pull requests merged in 2019-09, with the labels that each got.

#412 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#413 Set zone's visible column default true and update existing rows
  db/migrate/20190909195908_set_zone_visible_column_default_true.rb
  spec/migrations/20190909195908_set_zone_visible_column_default_true_spec.rb
Labels: blocker, bug, ivanchuk/yes

#415 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation

#420 Connect CloudNetwork, NetworkPort and SecurityGroup to ResourceGroup
  db/migrate/20190930054405_add_resource_group_id_to_cloud_network.rb
  db/migrate/20190930054416_add_resource_group_id_to_network_port.rb
  db/migrate/20190930054424_add_resource_group_id_to_security_group.rb
Labels: enhancement

#419 Handle faulty v2_key while upgrading ansible (with specs)
  db/migrate/20190617191109_move_awx_credentials_to_authentications.rb
  spec/migrations/20190617191109_move_awx_credentials_to_authentications_spec.rb
Labels: bug, ivanchuk/yes
