Repository ManageIQ/manageiq-schema, pull requests merged in 2019-02, with the labels that each got.

#331 Remove manageiq-gems-pending in favor of manageiq-password
  manageiq-schema.gemspec
Labels: dependencies, technical debt

#336 Add comments to the miq_tasks table
  db/migrate/20190214125845_add_comments_to_miq_tasks_table.rb
  spec/automated_review/column_documentation_spec.rb
Labels: documentation

#337 Create a new migration to fix special characters in the rabbitmq password
  db/migrate/20181012160010_remove_special_characters_from_ansible_rabbitmq_password.rb
  db/migrate/20181012161000_remove_special_characters_from_ansible_rabbitmq_password_two.rb
  spec/migrations/20181012161000_remove_special_characters_from_ansible_rabbitmq_password_two_spec.rb
Labels: blocker, bug, hammer/yes

#339 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#327 Use views for the metrics and metric_rollups tables
  db/migrate/20190122213042_use_views_for_metrics.rb
  lib/migration_helper.rb
Labels: enhancement, hammer/no

#342 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes
