Repository ManageIQ/manageiq-schema, pull requests merged in 2019-12, with the labels that each got.

#157 Remove Middleware Hawkular Schema
  db/migrate/20191126204129_remove_middleware_columns_in_event_streams.rb
  db/migrate/20191126204211_remove_middleware_tables.rb
Labels: cleanup, gaprindashvili/no, providers/middleware

#441 Ignore update_all
  .rubocop_local.yml
  manageiq-schema.gemspec
Labels: tools

#442 Track if a Storage is in maintenance_mode or not
  db/migrate/20191210135022_add_maintenance_mode_to_storages.rb
Labels: bug, providers/virtual

#443 Subclass Storages by provider
  db/migrate/20191210162908_add_type_to_storages.rb
  db/migrate/20191210163518_subclass_storages.rb
  spec/migrations/20191210163518_subclass_storages_spec.rb
Labels: enhancement, providers/virtual

#444 Fix splitting storages for archived hosts
  db/migrate/20190729170013_split_storages_per_ems.rb
  spec/migrations/20190729170013_split_storages_per_ems_spec.rb
Labels: bug
