Repository ManageIQ/manageiq-schema, pull requests merged in 2019-08, with the labels that each got.

#404 Add initiator_type to miq_requests
  db/migrate/20190731175747_add_initiator_type_to_miq_requests.rb
Labels: enhancement, ivanchuk/no

#400 Remove the local configuration script sources for embedded ansible
  db/migrate/20190726204302_remove_local_default_embedded_ansible_repos.rb
  spec/migrations/20190726204302_remove_local_default_embedded_ansible_repos_spec.rb
Labels: data, embedded ansible, ivanchuk/yes

#405 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#401 Migrate with cleared schema cache
  lib/manageiq/schema/engine.rb
  lib/manageiq/schema/migrate_with_cleared_schema_cache.rb
Labels: blocker, changelog/yes, ivanchuk/yes

#406 Move the embedded ansible proxy settings to a top level git repo key
  db/migrate/20190809193031_move_embedded_ansible_proxy_setting_to_git_repository_proxy_settings.rb
  spec/migrations/20190809193031_move_embedded_ansible_proxy_setting_to_git_repository_proxy_settings_spec.rb
Labels: blocker, bug, data, embedded ansible, ivanchuk/yes

#403 Guest devices should also have ems refs
  db/migrate/20190801025156_add_ems_ref_to_guest_device.rb
Labels: enhancement, schema

#402 Disk keys should be stored
  db/migrate/20190801025013_add_ems_ref_to_disk.rb
Labels: enhancement, schema

#408 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#409 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#411 Add a speed column to guest_devices
  db/migrate/20190830133434_add_speed_to_guest_devices.rb
Labels: enhancement
