Repository ManageIQ/manageiq-schema, pull requests merged in 2019-10, with the labels that each got.

#410 Rename service display column to visible.
  db/migrate/20190827141149_rename_service_display_to_visible.rb
Labels: bug, changelog/yes, ivanchuk/no

#422 Drop the quadicon settings from Users' settings as it's obsolete
  db/migrate/20191002103406_remove_quadicon_settings.rb
  spec/migrations/20191002103406_remove_quadicon_settings_spec.rb
Labels: ivanchuk/no, technical debt

#424 Add indexes to various tables
  db/migrate/20191017211747_add_general_indexes.rb
Labels: index, performance
