Repository ManageIQ/manageiq-schema, pull requests merged in 2019-05, with the labels that each got.

#368 Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#369 Change plugin common methods to class methods
  lib/manageiq/schema/engine.rb
Labels: changelog/no, enhancement

#367 Add price to service templates.
  db/migrate/20190513155251_add_price_to_service_templates.rb
Labels: changelog/yes, enhancement, hammer/no

#373 Add columns of price and currency to services.
  db/migrate/20190520174739_add_price_to_services.rb
Labels: changelog/yes, enhancement, hammer/no

#372 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#371 Introduce :firmware_registry and :firmware_binary tables
  db/migrate/20190514115219_create_firmware_registries.rb
  db/migrate/20190514124322_create_firmware_binaries.rb
  db/migrate/20190517093412_create_firmware_targets.rb
  db/migrate/20190517093516_create_firmware_binary_firmware_targets.rb
Labels: enhancement, schema

#375 [Changelog] Update for Sprint 112
  CHANGELOG.md
Labels: documentation

#377 Add guid to miq_databases
  db/migrate/20190531161732_add_guid_to_miq_databases.rb
  spec/migrations/20190531161732_add_guid_to_miq_databases_spec.rb
Labels: enhancement

#379 Fix ActiveRecord Migration version
  db/migrate/20190531161732_add_guid_to_miq_databases.rb
Labels: bug
