Repository ManageIQ/manageiq-schema, pull requests merged in 2019-01, with the labels that each got.

#320 Removes OpenStack Cinder event Worker Rows
  db/migrate/20190108163812_remove_cinder_manager_event_worker_rows.rb
  spec/migrations/20190108163812_remove_cinder_manager_event_worker_rows_spec.rb
Labels: gaprindashvili/yes, hammer/yes

#321 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#319 Rename WebsocketWorker to RemoteConsoleWorker
  db/migrate/20190108135546_rename_websocket_to_remote_console.rb
  spec/migrations/20190108135546_rename_websocket_to_remote_console_spec.rb
Labels: hammer/no

#330 Add a schema_migrations_ran
  db/migrate/20171031010000_add_schema_migrations_ran.rb
Labels: blocker, bug, hammer/yes

#324 Add multiattach field to CloudVolume
  db/migrate/20190110201414_add_multi_attachment_to_cloud_volume.rb
Labels: enhancement, providers/cloud

#333 [Changelog] Update for Hammer-2
  CHANGELOG.md
Labels: documentation
