Repository ManageIQ/manageiq-schema, pull requests merged in 2020-12, with the labels that each got.

#538 Fix CloudVolume* STI types on older CinderManagers
  db/migrate/20201202172818_fix_cinder_manager_cloud_volumes.rb
  spec/migrations/20201202172818_fix_cinder_manager_cloud_volumes_spec.rb
Labels: bug, data

#525 Rename TagMapping resource_type for Amazon Vms and Images
  db/migrate/20201022201901_update_amazon_tag_mapper_resource_type.rb
  spec/migrations/20201022201901_update_amazon_tag_mapper_resource_type_spec.rb
Labels: kasparov/no

#539 Data migration to cover edge conditions after control explorer split
  db/migrate/20201202164337_control_explorer_split_feature_mapping.rb
  spec/migrations/20201202164337_control_explorer_split_feature_mapping_spec.rb
Labels: cleanup

#537 Implement Host initiators
  db/migrate/20201111154314_create_host_initiators.rb
  db/migrate/20201124063738_create_san_addresses.rb
Labels: enhancement, providers/storage
