Repository ManageIQ/manageiq-schema, pull requests merged in 2020-05, with the labels that each got.

#474 Fix the dummy app's database.yml user/password
  spec/dummy/config/database.yml
Labels: bug

#475 Move database.yml to database.tmpl.yml and copy it for CI
  README.md
  bin/setup
  spec/dummy/config/database.tmpl.yml
Labels: test

#467 Add new failed_login_attempts column to the Users table
  db/migrate/20200409175736_add_failed_login_attempts_to_users.rb
  spec/migrations/20200409175736_add_failed_login_attempts_to_users_spec.rb
Labels: enhancement, schema

#464 Renamed foreman features to ems_configuration and adjusted roles
  db/migrate/20200331150436_rename_foreman_features.rb
  spec/migrations/20200331150436_rename_foreman_features_spec.rb
Labels: data, enhancement

#465 Add columns to improve automate object looking up performance
  db/migrate/20200325170358_add_domain_and_relative_path_to_automate.rb
  spec/migrations/20200325170358_add_domain_and_relative_path_to_automate_spec.rb
Labels: enhancement, performance

#478 Rename file missing _spec.rb. Rspec expects spec/**/*_spec.rb
  spec/automated_review/data_migrations_need_tests_spec.rb
  spec/migrations/20171011180000_move_openstack_refresher_settings_spec.rb
Labels: bug

#477 Remove most of VmdbDatabase and friends
  db/migrate/20200508150740_remove_vmdb_database_tables.rb
  db/migrate/20200512161742_remove_vmdb_database_settings.rb
  spec/migrations/20200512161742_remove_vmdb_database_settings_spec.rb
Labels: schema, technical debt

#483 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#481 Migration to update startpage entry for chargeback/explorer
  db/migrate/20200512201614_update_chargeback_startpage.rb
  spec/migrations/20200512201614_update_chargeback_startpage_spec.rb
Labels: data, enhancement

#480 Adjusted chargeback rates features for de-explorerization
  db/migrate/20200513123702_adjust_chargeback_rates_features.rb
  spec/migrations/20200513123702_adjust_chargeback_rates_features_spec.rb
Labels: data, enhancement

#484 Update schema to match manageiq rails version
  manageiq-schema.gemspec
Labels: dependencies, jansa/yes?

#468 add system flag to dialogs
  db/migrate/20200424183342_add_read_only_to_dialogs.rb
Labels: schema

#486 Migration for Startpage url updates for CB Assignments
  db/migrate/20200520182548_update_chargeback_assignments_startpage.rb
  spec/migrations/20200520182548_update_chargeback_assignments_startpage_spec.rb
Labels: enhancement, jansa/yes?

#485 change hardware mem usage to bigint
  db/migrate/20200519213913_change_hardware_mem_types.rb
  spec/migrations/20200519213913_change_hardware_mem_types_spec.rb
Labels: enhancement, schema
