Repository ManageIQ/manageiq-schema, pull requests merged in 2020-02, with the labels that each got.

#457 Remove RH domain
  db/migrate/20200211181329_drop_red_hat_domain.rb
  spec/migrations/20200211181329_drop_red_hat_domain_spec.rb
Labels: data, technical debt

#459 Add "thin" and "format" columns to disk
  db/migrate/20200219125312_add_thin_and_format_to_disk.rb
Labels: enhancement

#460 Remove MiqRegion#migrations_ran
  db/migrate/20200227195911_drop_region_migrations_ran.rb
Labels: technical debt
