Repository ManageIQ/manageiq-schema, pull requests merged in 2020-10, with the labels that each got.

#496 Delete any worker records that have a JSON queue_name
  db/migrate/20200717181436_delete_workers_with_json_queue_names.rb
  spec/migrations/20200717181436_delete_workers_with_json_queue_names_spec.rb
Labels: bug

#518 Fix require of manageiq-schema
  lib/manageiq-schema.rb
  spec/dummy/config/application.rb
Labels: bug

#519 Schema dumper fixes
  lib/manageiq/schema/schema_dumper.rb
  lib/manageiq/schema/schema_statements.rb
Labels: bug

#520 Add orchestration stacks reference to configured systems
  db/migrate/20201008185329_add_orchestration_stacks_to_configured_systems.rb
Labels: enhancement, providers/configuration

#521 Update vms table 'format' column comment
  db/migrate/20201012120000_update_comment_to_vms_table_format.rb
Labels: enhancement

#524 Drop unused / typo timestamp column (fix for Rails 6)
  db/migrate/20151104115400_create_chargeback_tiers.rb
Labels: bug

#488 Use manageiq style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-schema.gemspec
Labels: developer, enhancement

#523 Introduce Openstack cloud manager child manager migration
  db/migrate/20201019211215_create_legacy_managers.rb
  spec/migrations/20201019211215_create_legacy_managers_spec.rb
Labels: data, enhancement
