Repository ManageIQ/manageiq-schema, pull requests merged in 2020-01, with the labels that each got.

#448 Add description_string to MiqGroup
  db/migrate/20200109190758_add_desc_string_to_miq_group.rb
Labels: enhancement

#450 Upgrade existing dropbox depots to the support tool
  db/migrate/20200122215829_upgrade_dropbox_to_support_tool.rb
  spec/migrations/20200122215829_upgrade_dropbox_to_support_tool_spec.rb
Labels: enhancement

#453 Update README.md with steps to run tests in local dev env
  README.md
Labels: documentation

#449 Fix issue with orch stacks still having references to deleted ems
  db/migrate/20181016140921_migrate_orch_stacks_to_have_ownership_concept.rb
  spec/migrations/20181016140921_migrate_orch_stacks_to_have_ownership_concept_spec.rb
Labels: bug, data
