Repository ManageIQ/manageiq-schema, pull requests merged in 2020-09, with the labels that each got.

#507 Fix RSpec warning on raise_error
  spec/migrations/20200409175736_add_failed_login_attempts_to_users_spec.rb
Labels: bug, test

#511 Add target platform to the configuration profiles
  db/migrate/20200914005000_add_target_platform_to_configuration_profiles.rb
Labels: enhancement

#508 Replace Vim* types in CustomizationSpec#spec
  db/migrate/20200910145925_remove_vim_types_from_customization_specs.rb
  spec/migrations/20200910145925_remove_vim_types_from_customization_specs_spec.rb
Labels: bug

#514 Rename the ContainerLabelTagMapping table to ProviderTagMapping
  db/migrate/20200921142257_rename_container_label_tag_mapping.rb
Labels: refactoring

#503 Add relationship from sessions to users
  db/migrate/20200819184941_add_user_to_sessions.rb
Labels: enhancement

#504 Fix `db/schema.rb` generation
  lib/manageiq/schema/command_recorder.rb
  lib/manageiq/schema/engine.rb
  lib/manageiq/schema/schema_dumper.rb
  lib/manageiq/schema/schema_statements.rb
  lib/migration_helper.rb
Labels: enhancement

#515 Add vendor to configured_systems
  db/migrate/20200924151045_add_vendor_to_configured_systems.rb
Labels: enhancement

#505 Added schema changes for Autosde provider
  db/migrate/20200519141015_create_storage_resources.rb
  db/migrate/20200521150213_create_storage_services.rb
  db/migrate/20200524074928_create_storage_service_resource_attachments.rb
  db/migrate/20200608163713_create_physical_storage_families.rb
  db/migrate/20200806112501_expand_cloud_volume.rb
  db/migrate/20200922180455_add_family_to_physical_storages.rb
Labels: enhancement, providers/storage
