Repository ManageIQ/manageiq-schema, pull requests merged in 2020-04, with the labels that each got.

#455 MiqAeNamespace should use ancestry instead of acts_as_tree
  db/migrate/20200221200855_add_ancestry_to_miq_ae_namespace.rb
  manageiq-schema.gemspec
  spec/migrations/20200221200855_add_ancestry_to_miq_ae_namespace_spec.rb
Labels: performance

#469 Remove VimString objects from Notification.options
  db/migrate/20200427122455_remove_vim_strings_from_notifications.rb
  spec/migrations/20200427122455_remove_vim_strings_from_notifications_spec.rb
Labels: bug, jansa/yes?

#473 DB migrations for NSX-T provider
  db/migrate/20200428143000_create_network_service.rb
  db/migrate/20200428143500_create_security_policy.rb
  db/migrate/20200428144000_add_description_to_cloud_network.rb
Labels: enhancement
