Repository ManageIQ/manageiq-schema, pull requests merged in 2021-07, with the labels that each got.

#582 Rename Flavors cpu attributes for consistency with hardware
  db/migrate/20210622184700_rename_flavors_cpus_to_match_hardware.rb
  db/migrate/20210629160030_fix_flavor_cpu_attributes.rb
  spec/migrations/20210629160030_fix_flavor_cpu_attributes_spec.rb
Labels: technical debt

#576 replace miq_set relationships with miq_set_memberships table
  db/migrate/20210519200613_add_miq_set_memberships.rb
  db/migrate/20210519204247_move_miq_set_memberships.rb
  spec/migrations/20210519204247_move_miq_set_memberships_spec.rb
  spec/support/table_list.txt
Labels: enhancement

#587 Update IBM Cloud 'vendor' attribute to 'ibm_cloud'
  db/migrate/20210718074605_update_ibm_vendor_to_ibm_cloud.rb
  spec/migrations/20210718074605_update_ibm_vendor_to_ibm_cloud_spec.rb
Labels: data

#585 Set existing VMware InfraManagers' default_endpoint.port to 443 and verify_ssl to 0
  db/migrate/20210716175712_fix_vmware_infra_endpoint.rb
  spec/migrations/20210716175712_fix_vmware_infra_endpoint_spec.rb
Labels: data, technical debt

#589 Fix brakeman issues with rename_class_references helper method.
  lib/migration_helper.rb
Labels: bug

#590 Fix issue where wrong variable was chomped
  lib/migration_helper.rb
Labels: bug, lasker/yes?

#593 Remove unused column old_ems_id from multiple container tables
  db/migrate/20210728143006_remove_old_ems_id_from_container_tables.rb
Labels: technical debt

#592 Add spec generator for migration generator
  lib/generators/migration/migration_generator.rb
  lib/generators/migration/templates/migration_spec.rb.tt
  spec/lib/generators/migration_generator_spec.rb
Labels: developer, enhancement

#595 Add `#options` to Endpoints
  db/migrate/20210729132849_add_options_to_endpoints.rb
Labels: enhancement
