Repository ManageIQ/manageiq-schema, pull requests merged in 2021-08, with the labels that each got.

#594 Modify host initiators listing page
  db/migrate/20210726060426_add_fields_to_host_initiators.rb
Labels: enhancement

#591 Remove job_proxy_dispatcher_interval settings
  db/migrate/20210727140323_rename_job_proxy_dispatcher_settings.rb
  spec/migrations/20210727140323_rename_job_proxy_dispatcher_settings_spec.rb
Labels: refactoring, data

#588 Remove rhn and rhms/satellite columns
  db/migrate/20210720180318_remove_rh_subscription_columns.rb
  db/migrate/20210726194608_delete_rhn_authentications.rb
  db/migrate/20210810191933_remove_update_repo_names_from_settings.rb
  spec/migrations/20210726194608_delete_rhn_authentications_spec.rb
  spec/migrations/20210810191933_remove_update_repo_names_from_settings_spec.rb
Labels: enhancement

#598 added columns and props for health state of cloud volume
  db/migrate/20210808125201_add_health_state_to_cloud_volume.rb
Labels: enhancement

#597 Update table_list.txt
  spec/support/table_list.txt
Labels: cleanup

#600 More accurately check schema dumper lines
  spec/schema/schema_dumper_spec.rb
Labels: test

#601 Remove old memcache_server_opts from settings_changes
  db/migrate/20210817182147_remove_memcache_server_opts.rb
  spec/migrations/20210817182147_remove_memcache_server_opts_spec.rb
Labels: technical debt, data

#602 Convert NetworkRouter#admin_state_up from varchar to boolean
  db/migrate/20210819145618_update_network_router_admin_state_up.rb
  spec/migrations/20210819145618_update_network_router_admin_state_up_spec.rb
Labels: bug
