Repository ManageIQ/manageiq-schema, pull requests merged in 2021-02, with the labels that each got.

#551 Data Migration for Conditions Startpage url update
  db/migrate/20210112004301_update_conditions_startpage_url_after_de_explorization.rb
  spec/migrations/20210112004301_update_conditions_startpage_url_after_de_explorization_spec.rb
Labels: data, enhancement

#549 Data Migration for Alert Profiles Startpage url update
  db/migrate/20210112001749_update_alert_profiles_startpage_url_after_de_explorization.rb
  spec/migrations/20210112001749_update_alert_profiles_startpage_url_after_de_explorization_spec.rb
Labels: data, enhancement

#557 Introducing VolumeMapping
  db/migrate/20201220133400_create_volume_mappings.rb
  spec/support/table_list.txt
Labels: enhancement, providers/storage

#548 Data Migration for Alerts Startpage url update
  db/migrate/20210112000610_update_alerts_startpage_url_after_de_explorization.rb
  spec/migrations/20210112000610_update_alerts_startpage_url_after_de_explorization_spec.rb
Labels: data, enhancement

#558 Added :type to volume_mapping and host_initiator
  db/migrate/20210211174438_add_type_to_volume_mappings_and_host_initiators.rb
Labels: bug, providers/storage

#547 Start page url data migration for Actions De-explorization
  db/migrate/20201230005555_update_startpage_shortcut_after_actions_de_explorization.rb
  spec/migrations/20201230005555_update_startpage_shortcut_after_actions_de_explorization_spec.rb
Labels: data, enhancement

#559 Add a JSONB Capabilities to EMS and Providers
  db/migrate/20210217201401_add_capabilities_to_ext_management_system.rb
  db/migrate/20210217201406_add_capabilities_to_provider.rb
Labels: schema

#560 Feature identifier updates migration for Configuration Script
  db/migrate/20210218230058_update_configuration_script_features.rb
  spec/migrations/20210218230058_update_configuration_script_features_spec.rb
Labels: data, enhancement

#562 Add contributing guidelines
  CONTRIBUTING.md
Labels: documentation
