Repository ManageIQ/manageiq-schema, pull requests merged in 2021-01, with the labels that each got.

#541 Data Migration for Policy Profile Startpage url update
  db/migrate/20201227173629_update_startup_shortcut_after_policy_profile_deexplorization.rb
  spec/migrations/20201227173629_update_startup_shortcut_after_policy_profile_deexplorization_spec.rb
Labels: data, enhancement

#544 Policy Simulation startpage url migration to set it to new path
  db/migrate/20210106180202_update_policy_rsop_startpage_url.rb
  spec/migrations/20210106180202_update_policy_rsop_startpage_url_spec.rb
Labels: data, enhancement

#545 Policy Log startpage url migration to set it to new path
  db/migrate/20210106201124_update_policy_log_startpage_url.rb
  spec/migrations/20210106201124_update_policy_log_startpage_url_spec.rb
Labels: data, enhancement

#554 Update manageiq-style
  .codeclimate.yml
Labels: developer

#552 [rails6][schema_dumper.rb] Use table_name properly
  lib/manageiq/schema/schema_dumper.rb
  lib/tasks_private/spec.rake
  spec/schema/schema_dumper_spec.rb
  spec/support/table_list.txt
Labels: bug

#553 Subclass CinderManagers under Openstack
  db/migrate/20210118185402_subclass_cinder_manager_openstack.rb
  spec/migrations/20210118185402_subclass_cinder_manager_openstack_spec.rb
Labels: data

#492 set vm ancestry from relationship resource info
  db/migrate/20200607025146_add_ancestry_to_vm.rb
  spec/migrations/20200607025146_add_ancestry_to_vm_spec.rb
Labels: enhancement

#542 Data Migration for Policy Startpage url update
  db/migrate/20210105011714_update_policy_startpage_url_after_de_explorization.rb
  spec/migrations/20210105011714_update_policy_startpage_url_after_de_explorization_spec.rb
Labels: enhancement
