Repository ManageIQ/manageiq-schema, pull requests merged in 2021-11, with the labels that each got.

#579 Loosen manageiq-password to < 2
  manageiq-schema.gemspec
  spec/dummy/certs/v2_key
  spec/spec_helper.rb
Labels: dependencies

#607 Drop database_backups table
  db/migrate/20210831202037_drop_database_backups_table.rb
  spec/support/table_list.txt
Labels: technical debt

#616 Update dummy app to Rails 6.0.1.4
  .gitignore
  .rubocop_local.yml
  lib/tasks_private/spec.rake
  spec/automated_review/belongs_to_required_by_default_spec.rb
  spec/dummy/.gitignore
  spec/dummy/README.md
  spec/dummy/app/assets/config/manifest.js
  spec/dummy/app/assets/javascripts/application.js
  spec/dummy/app/assets/javascripts/cable.js
  spec/dummy/app/assets/stylesheets/application.css
  spec/dummy/app/controllers/application_controller.rb
  spec/dummy/app/javascript/channels/consumer.js
  spec/dummy/app/javascript/channels/index.js
  spec/dummy/app/javascript/packs/application.js
  spec/dummy/app/jobs/application_job.rb
  spec/dummy/app/views/layouts/application.html.erb
  spec/dummy/bin/bundle
  spec/dummy/bin/setup
  spec/dummy/bin/update
  spec/dummy/bin/yarn
  spec/dummy/config/application.rb
  spec/dummy/config/boot.rb
  spec/dummy/config/cable.yml
  spec/dummy/config/credentials.yml.enc
  spec/dummy/config/environments/development.rb
  spec/dummy/config/environments/production.rb
  spec/dummy/config/environments/test.rb
  spec/dummy/config/initializers/application_controller_renderer.rb
  spec/dummy/config/initializers/assets.rb
  spec/dummy/config/initializers/content_security_policy.rb
  spec/dummy/config/initializers/new_framework_defaults.rb
  spec/dummy/config/initializers/session_store.rb
  spec/dummy/config/locales/en.yml
  spec/dummy/config/puma.rb
  spec/dummy/config/routes.rb
  spec/dummy/config/secrets.yml
  spec/dummy/config/spring.rb
  spec/dummy/config/storage.yml
  spec/dummy/db/seeds.rb
  spec/dummy/lib/tasks/.keep
  spec/dummy/package.json
  spec/dummy/public/404.html
  spec/dummy/public/422.html
  spec/dummy/public/500.html
  spec/dummy/public/robots.txt
  spec/dummy/storage/.keep
  spec/dummy/test/application_system_test_case.rb
  spec/dummy/test/channels/application_cable/connection_test.rb
  spec/dummy/test/controllers/.keep
  spec/dummy/test/fixtures/.keep
  spec/dummy/test/fixtures/files/.keep
  spec/dummy/test/helpers/.keep
  spec/dummy/test/integration/.keep
  spec/dummy/test/mailers/.keep
  spec/dummy/test/models/.keep
  spec/dummy/test/system/.keep
  spec/dummy/test/test_helper.rb
  spec/dummy/tmp/pids/.keep
  spec/dummy/vendor/.keep
Labels: test

#613 Remove cockpit from assigned services
  db/migrate/20211022131607_drop_cockpit.rb
  spec/migrations/20211022131607_drop_cockpit_spec.rb
Labels: technical debt

#618 Delete hawkular endpoints and authentications
  db/migrate/20211119152213_remove_hawkular_authentications.rb
  spec/migrations/20211119152213_remove_hawkular_authentications_spec.rb
Labels: data

#619 Creation of host initiator group
  db/migrate/20211124180240_add_type_to_host_initiator_groups.rb
Labels: enhancement
