Repository ManageIQ/manageiq-schema, pull requests merged in 2021-06, with the labels that each got.

#580 Migrate one more feature renamed previously
  db/migrate/20210521192754_update_product_features_where_identifier_was_renamed_since_lasker.rb
  spec/migrations/20210521192754_update_product_features_where_identifier_was_renamed_since_lasker_spec.rb
Labels: data, enhancement, lasker/no

#575 Fix Redhat NetworkManager resource STI types
  db/migrate/20210506225927_fix_redhat_network_manager_sti_type.rb
  spec/migrations/20210506225927_fix_redhat_network_manager_sti_type_spec.rb
Labels: bug, data

#581 Enable ems_storage* feature if ems_block_storage* is enabled
  db/migrate/20210601125525_ensure_ems_storage_features.rb
  spec/migrations/20210601125525_ensure_ems_storage_features_spec.rb
Labels: data, enhancement

#583 Fix VPC Flavors STI type name
  db/migrate/20210625185428_fix_vpc_flavors_sti.rb
  spec/migrations/20210625185428_fix_vpc_flavors_sti_spec.rb
Labels: bug
