Repository ManageIQ/manageiq-schema, pull requests merged in 2022-09, with the labels that each got.

#662 rspec-mocks 3.10.3 requires "with" to be explicit with hashes vs. kwargs
  spec/migrations/20180606155924_move_ansible_container_secrets_into_database_spec.rb
Labels: test, ruby3

#664 drop rails 60 build
  .github/workflows/ci.yaml
Labels: rails6.1

#663 remove ws_cockpit role from /server/roles
  db/migrate/20220909190221_drop_cockpit_role.rb
  spec/migrations/20220909190221_drop_cockpit_role_spec.rb
Labels: bug
