Repository ManageIQ/manageiq-schema, pull requests merged in 2022-11, with the labels that each got.

#670 Remove VimStrings from CustomAttribute#serialized_value
  db/migrate/20221111201223_remove_vim_strings_from_custom_attributes.rb
  spec/migrations/20221111201223_remove_vim_strings_from_custom_attributes_spec.rb
Labels: bug, oparin/yes?

#671 Remove VimString from MiqRequestTask#options
  db/migrate/20221114165219_remove_vim_string_from_miq_request_task_options.rb
  spec/migrations/20221114165219_remove_vim_string_from_miq_request_task_options_spec.rb
Labels: bug, data, oparin/yes?

#673 Add server profile template table for PhysicalServer
  db/migrate/20221117080009_create_physical_server_profile_templates.rb
  spec/support/table_list.txt
Labels: enhancement
