Repository ManageIQ/manageiq-schema, pull requests merged in 2022-05, with the labels that each got.

#645 Add physical server profile
  db/migrate/20220401093502_create_physical_server_profiles.rb
  spec/support/table_list.txt
Labels: enhancement

#647 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#643 Add new field to save customized message for validation
  db/migrate/20220324143540_add_validation_message_to_dialog_fields.rb
Labels: enhancement

#644 added server placement group
  db/migrate/20220407210610_placement_group_additions.rb
  spec/support/table_list.txt
Labels: enhancement, providers/cloud

#649 Add ExtManagementSystem#last_refresh_success_date
  db/migrate/20220527165347_add_last_refresh_success_date.rb
Labels: enhancement
