Repository ManageIQ/manageiq-schema, pull requests merged in 2022-06, with the labels that each got.

#651 Start page url data migration for Services De-explorization
  db/migrate/20220629110748_update_startpage_shortcut_after_services_de_explorization.rb
  spec/migrations/20220629110748_update_startpage_shortcut_after_services_de_explorization_spec.rb
Labels: enhancement

#650 Migrate Authentication#become_method out of :options
  db/migrate/20220617140212_add_become_method_to_authentications.rb
  db/migrate/20220617140542_move_become_method_from_options.rb
  spec/migrations/20220617140542_move_become_method_from_options_spec.rb
Labels: enhancement, data

#652 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer
