Repository ManageIQ/manageiq-schema, pull requests merged in 2022-02, with the labels that each got.

#634 Remove Hakiri
  README.md
Labels: cleanup, developer

#635 Support rails 6.1
  .travis.yml
  Gemfile
  db/migrate/20190617191109_move_awx_credentials_to_authentications.rb
  manageiq-schema.gemspec
  spec/migrations/20190617191109_move_awx_credentials_to_authentications_spec.rb
  spec/spec_helper.rb
Labels: dependencies, rails6.1

#636 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/ci/after_script
  bin/setup
  bin/update
  bundler.d/.gitkeep
  manageiq-schema.gemspec
Labels: test

#637 Ensure we connect to PG over TCP and not a socket in Github Actions
  .github/workflows/ci.yaml
Labels: bug, test

#639 Ensure code climate only reports on 2.7/6.1
  .github/workflows/ci.yaml
Labels: test

#640 Add Build History Graph to README.md
  README.md
Labels: developer, test

#638 Service request connected to Automation request
  db/migrate/20220202122417_add_parent_relation_to_miq_requests.rb
Labels: enhancement

#642 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
