Repository ManageIQ/manageiq-schema, pull requests merged in 2023-05, with the labels that each got.

#689 Delete old Workflow/WorkflowInstance tables
  db/migrate/20230425153512_drop_workflow_workflow_instance.rb
  spec/support/table_list.txt
Labels: enhancement, providers/automation

#691 Converge batch_size and concurrent_requests
  db/migrate/20230522194044_move_concurrent_requests_settings_to_vmware.rb
  spec/migrations/20230522194044_move_concurrent_requests_settings_to_vmware_spec.rb
Labels: data

#692 Set the instance_type for VPC provision requests
  db/migrate/20230525200407_fix_vpc_provision_instance_type.rb
  spec/migrations/20230525200407_fix_vpc_provision_instance_type_spec.rb
Labels: bug, data
