Repository ManageIQ/manageiq-schema, pull requests merged in 2024-02, with the labels that each got.

#716 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#717 Remove Openstack NetworkManager metrics worker records
  db/migrate/20240214165402_remove_openstack_network_manager_metrics_collector_workers.rb
  spec/migrations/20240214165402_remove_openstack_network_manager_metrics_collector_workers_spec.rb
Labels: bug, data, quinteros/yes

#719 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#720 Update audit managed resources queue task
  db/migrate/20240227184516_update_audit_managed_resources_queue_name.rb
  spec/migrations/20240227184516_update_audit_managed_resources_queue_name_spec.rb
Labels: bug, data, radjabov/yes?
