Repository ManageIQ/manageiq-schema, pull requests merged in 2024-11, with the labels that each got.

#765 Testing with ruby 3.2, 3.3
  .github/workflows/ci.yaml
Labels: ruby3.3

#766 Fix broken ci.yaml
  .github/workflows/ci.yaml
Labels: bug, radjabov/yes

#767 Allow test failures on 7.1 and 7.2 for now
  .github/workflows/ci.yaml
Labels: radjabov/yes?, rails7.1
