Repository ManageIQ/manageiq-schema, pull requests merged in 2024-08, with the labels that each got.

#741 Use ruby 3.1 and rails 7 for code coverage
  .github/workflows/ci.yaml
Labels: developer, test

#746 Drop no longer used linux_admin requirement
  manageiq-schema.gemspec
Labels: cleanup

#718 Update resource pool feature identifiers to infrastructure-specific
  db/migrate/20240516101409_updateresourcepoolidentifierstomiqproductfeatures.rb
  spec/migrations/20240516101409_updateresourcepoolidentifierstomiqproductfeatures_spec.rb
Labels: enhancement

#749 Cleanup naming of the migration
  db/migrate/20240516101409_update_resource_pool_identifiers_to_miq_product_features.rb
  spec/migrations/20240516101409_update_resource_pool_identifiers_to_miq_product_features_spec.rb
Labels: cleanup

#750 Update dummy app to Rails 7.0.8.4
  .github/workflows/ci.yaml
  Gemfile
  spec/dummy/.gitattributes
  spec/dummy/.gitignore
  spec/dummy/Rakefile
  spec/dummy/app/assets/stylesheets/application.css
  spec/dummy/app/javascript/channels/consumer.js
  spec/dummy/app/javascript/channels/index.js
  spec/dummy/app/javascript/packs/application.js
  spec/dummy/app/mailers/application_mailer.rb
  spec/dummy/app/models/application_record.rb
  spec/dummy/app/views/layouts/application.html.erb
  spec/dummy/bin/rails
  spec/dummy/bin/rake
  spec/dummy/bin/setup
  spec/dummy/bin/yarn
  spec/dummy/config.ru
  spec/dummy/config/application.rb
  spec/dummy/config/boot.rb
  spec/dummy/config/credentials.yml.enc
  spec/dummy/config/environment.rb
  spec/dummy/config/environments/development.rb
  spec/dummy/config/environments/production.rb
  spec/dummy/config/environments/test.rb
  spec/dummy/config/initializers/application_controller_renderer.rb
  spec/dummy/config/initializers/backtrace_silencers.rb
  spec/dummy/config/initializers/content_security_policy.rb
  spec/dummy/config/initializers/cookies_serializer.rb
  spec/dummy/config/initializers/filter_parameter_logging.rb
  spec/dummy/config/initializers/inflections.rb
  spec/dummy/config/initializers/mime_types.rb
  spec/dummy/config/initializers/permissions_policy.rb
  spec/dummy/config/initializers/wrap_parameters.rb
  spec/dummy/config/locales/en.yml
  spec/dummy/config/puma.rb
  spec/dummy/config/routes.rb
  spec/dummy/config/storage.yml
  spec/dummy/db/seeds.rb
  spec/dummy/package.json
  spec/dummy/test/test_helper.rb
  spec/dummy/tmp/storage/.keep
Labels: test, rails7, radjabov/yes?

#752 Reset resource_pool_infra product features
  db/migrate/20240830172702_reset_resource_pool_identifiers.rb
  spec/migrations/20240830172702_reset_resource_pool_identifiers_spec.rb
Labels: bug, data
