Repository ManageIQ/manageiq-schema, pull requests merged in 2024-10, with the labels that each got.

#762 Bump the rails gem minimum for CVEs
  manageiq-schema.gemspec
Labels: dependencies, radjabov/yes

#757 Add a migration to encrypt database password using scram-sha-256
  db/migrate/20241017013023_reencrypt_password_scramsha.rb
  spec/migrations/20241017013023_reencrypt_password_scramsha_spec.rb
Labels: enhancement, radjabov/yes

#763 Handle cases where the database connection does not use a password
  db/migrate/20241017013023_reencrypt_password_scramsha.rb
  spec/migrations/20241017013023_reencrypt_password_scramsha_spec.rb
Labels: bug

#756 Add rails 7.1 and 7.2 support
  .github/workflows/ci.yaml
  Gemfile
  db/migrate/20171103212526_move_zone_ntp_settings_to_settings.rb
  db/migrate/20180606083431_convert_quadicon_settings_keys.rb
  db/migrate/20181001131632_add_conversion_host_id_to_miq_request_tasks.rb
  db/migrate/20191002103406_remove_quadicon_settings.rb
  db/migrate/20200331150436_rename_foreman_features.rb
  db/migrate/20200512201614_update_chargeback_startpage.rb
  db/migrate/20200520182548_update_chargeback_assignments_startpage.rb
  db/migrate/20200520210200_update_chargeback_reports_startpage.rb
  db/migrate/20200910163718_adjust_control_explorer_startpage_entries.rb
  db/migrate/20201227173629_update_startup_shortcut_after_policy_profile_deexplorization.rb
  db/migrate/20201230005555_update_startpage_shortcut_after_actions_de_explorization.rb
  db/migrate/20210105011714_update_policy_startpage_url_after_de_explorization.rb
  db/migrate/20210106180202_update_policy_rsop_startpage_url.rb
  db/migrate/20210106200226_update_policy_export_startpage_url.rb
  db/migrate/20210106201124_update_policy_log_startpage_url.rb
  db/migrate/20210112000610_update_alerts_startpage_url_after_de_explorization.rb
  db/migrate/20210112001749_update_alert_profiles_startpage_url_after_de_explorization.rb
  db/migrate/20210112003720_update_events_startpage_url_after_de_explorization.rb
  db/migrate/20210112004301_update_conditions_startpage_url_after_de_explorization.rb
  db/migrate/20210315161230_update_automation_provider_startpage.rb
  db/migrate/20220629110748_update_startpage_shortcut_after_services_de_explorization.rb
  db/migrate/20230525200407_fix_vpc_provision_instance_type.rb
  lib/manageiq/schema/engine.rb
  lib/manageiq/schema/serialize_positional_to_kwargs_bridge.rb
  manageiq-schema.gemspec
  spec/dummy/config/application.rb
  spec/lib/generators/migration_generator_spec.rb
  spec/support/migration_helper.rb
Labels: enhancement, rails7.1, rails7.2
