Repository ManageIQ/manageiq-schema, pull requests merged in 2025-01, with the labels that each got.

#776 Allow the rails method to be called and change the result only when called from the migration
  .github/workflows/ci.yaml
  spec/migrations/20241017013023_reencrypt_password_scramsha_spec.rb
  spec/support/migration_name_helper.rb
Labels: test, rails7.1

#778 update manageiq-style
  manageiq-schema.gemspec
Labels: dependencies

#777 [MORPHY] Rexml rails version
  manageiq-schema.gemspec
Labels: dependencies, Mend: dependency security vulnerability

#780 Pin concurrent-ruby to < 1.3.5
  manageiq-schema.gemspec
Labels: dependencies
